'use strict';
const $=id=>document.getElementById(id);
let key=sessionStorage.getItem('rpg-worker-key')||'';
const fragment=new URLSearchParams(location.hash.slice(1));
if(fragment.has('key')){key=fragment.get('key');sessionStorage.setItem('rpg-worker-key',key);history.replaceState(null,'',location.pathname);}
let state=null,page='overview',records=[],testData=[],browseTarget=null,browseState=null,polling=false,setupDirty=false;
$('page-setup').addEventListener('input',()=>{setupDirty=true;});
$('page-setup').addEventListener('change',()=>{setupDirty=true;});
const titles={overview:'Overview',models:'Models',tests:'Test definitions',results:'Results',logs:'Logs',setup:'Worker setup'};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function showAlert(message,title='Notice'){ $('alert-title').textContent=title;$('alert-text').textContent=message;if(!$('alert').open)$('alert').showModal(); }
function toast(text){$('toast').textContent=text;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),3500);}
async function api(path,body){const options={headers:{Authorization:'Bearer '+key}};if(body!==undefined){options.method='POST';options.headers['Content-Type']='application/json';options.body=JSON.stringify(body);}const r=await fetch(path,options);if(r.status===403){if(!$('login').open)$('login').showModal();throw Error('Pair this browser with the worker.');}if(!r.ok){let msg='Request failed';try{msg=(await r.json()).error||msg;}catch{}throw Error(msg);}if(r.headers.get('Content-Type')?.includes('application/json'))return r.json();return r.blob();}
function on(id,fn){$(id).addEventListener('click',async()=>{try{await fn();}catch(e){showAlert(e.message);}});}
function button(text,fn,cls){const b=el('button',text,cls);b.addEventListener('click',async()=>{try{await fn();}catch(e){showAlert(e.message);}});return b;}
function setPage(name){page=name;document.querySelectorAll('.page').forEach(n=>n.classList.toggle('hidden',n.id!=='page-'+name));document.querySelectorAll('nav button').forEach(n=>n.classList.toggle('selected',n.dataset.page===name));$('page-title').textContent=titles[name];if(name==='tests')loadTests().catch(e=>showAlert(e.message));if(name==='results')loadResults().catch(e=>showAlert(e.message));}
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>setPage(b.dataset.page)));
document.querySelectorAll('.close-dialog').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
function render(s){state=s;const p=s.report?.plan;const busy=s.busy;$('connection').textContent='● Connected to worker';$('state-badge').textContent=s.state.toUpperCase().replaceAll('_',' ');$('demo').classList.toggle('hidden',!s.demo);$('message').textContent=s.message;$('gpu').textContent=s.report?.gpu?.name||(s.demo?'SIMULATED GTX 1080':'Your GPU worker');$('pending').textContent=p?.pending??'—';$('complete').textContent=p?.complete??'—';$('session-complete').textContent=s.completed_now;$('loads').textContent=p?.model_loads??'—';$('current').textContent=s.current?Object.entries(s.current).map(([k,v])=>k+': '+v).join(' · '):s.message;
$('progress').max=Math.max(1,(p?.pending??0)+s.completed_now);$('progress').value=s.completed_now;
['preflight','run','rescan','prepare','save-setup','new-test','import-example','refresh-results','export','enable-remote','disable-remote'].forEach(id=>$(id).disabled=busy);
$('pause').disabled=s.state!=='running';$('resume').disabled=s.state!=='paused';$('stop-model').disabled=!['running','paused'].includes(s.state);$('stop').disabled=!busy;$('restart').classList.toggle('hidden',!s.restart_required);$('run').disabled=busy||s.restart_required;
$('readiness').textContent=!s.report?'Not checked':s.report.preparation_only?(s.report.prepared?'Prepared (GPU not verified)':'Preparation blocked'):(s.report.ready?'Ready':'Needs attention');
const issues=$('issues');issues.replaceChildren();if(s.report){if(!s.report.issues.length)issues.append(el('p',s.report.note,'muted'));for(const i of s.report.issues){const row=el('div',undefined,'issue '+i.level);row.append(el('span',i.level.toUpperCase(),'label'),el('p',i.message));if(i.action){const b=button(i.label,async()=>{if(i.action.type==='setup'||i.action.type==='choose_folder'){setPage('setup');return;}if(i.action.type==='models'){setPage('models');return;}if(!confirm(i.label+'?\n\nOnly this action will be performed. Downloads may use substantial disk space.'))return;await api('/api/fix',{issue_id:i.id});await poll();});b.disabled=busy;row.append(b);}issues.append(row);}}
const plan=$('plan');plan.replaceChildren();for(const g of p?.groups||[]){const n=el('div',undefined,'plan-item');n.append(el('b',g.model_id),el('p',g.pending+' pending · '+g.complete+' complete · '+g.reason,'muted'));if(g.context)n.append(el('p','Automatic context allocation: '+g.context.allocated_tokens.toLocaleString()+' tokens','muted'));plan.append(n);}if(p&&!p.groups.length)plan.append(el('p','No models match this hardware tier.','muted'));
$('folder-note').textContent=s.report?.folder?.path?('Active folder: '+s.report.folder.path+' · '+s.report.folder.source):'No active model folder detected yet.';
renderModels();$('log-view').textContent=s.logs.map(l=>l.time+' ['+l.category+'] '+l.message).join('\n');$('remote-url').textContent=s.remote?.url||'';
if(!setupDirty&&!$('page-setup').contains(document.activeElement)){ $('backend').value=s.settings.backend;$('model-root').value=s.settings.model_root;$('lms-path').value=s.settings.lms_path;$('llama-path').value=s.settings.llama_path;$('sync-source').checked=s.settings.sync_source;$('publish-results').checked=s.settings.publish_results; }
}
let modelRenderSignature='';
function renderModels(){const list=$('model-list');const signature=JSON.stringify([state.models,state.busy,state.demo]);if(signature===modelRenderSignature)return;modelRenderSignature=signature;list.replaceChildren();for(const m of state.models){const card=el('article',undefined,'model-card');const heading=el('div',undefined,'section-header');heading.append(el('h3',m.name),el('span',m.quantization,'badge'));card.append(heading,el('p',(m.size_bytes/1e9).toFixed(2)+' GB download · '+(m.complete?'All shards found':'Missing shards')+' · '+(m.required_vram_gb===null?'Unassigned':m.required_vram_gb+' GB assigned')));const controls=el('div',undefined,'actions');const select=el('select');select.setAttribute('aria-label','VRAM for '+m.id);select.append(new Option('Choose VRAM',''));for(const t of [8,12,16,24,32,40,48,80])select.append(new Option(t+' GB',String(t)));select.value=String(m.required_vram_gb||'');controls.append(select);const save=button('Save VRAM',async()=>{if(!select.value)throw Error('Select a VRAM tier.');await api('/api/model/assign',{id:m.id,required_vram_gb:Number(select.value)});toast('Model assignment saved.');await api('/api/preflight',{});});save.disabled=state.busy||state.demo;controls.append(save);if(m.recommended_vram_gb){const accept=button('Accept recommended '+m.recommended_vram_gb+' GB',async()=>{await api('/api/model/assign',{id:m.id,required_vram_gb:m.recommended_vram_gb});await api('/api/preflight',{});});accept.disabled=state.busy||state.demo;controls.append(accept);}card.append(controls);if(m.errors.length)card.append(el('p',m.errors.join('; '),'error'));const d=el('details');d.append(el('summary','Files and discovery details'),el('pre',JSON.stringify({paths:m.paths,model_key:m.model_key,key_source:m.key_source,missing_shards:m.missing_shards},null,2)));card.append(d);list.append(card);}if(!state.models.length)list.append(el('article','No discovered models yet. Run preflight, then check the active folder.'));}
async function poll(){if(polling||!key)return;polling=true;try{render(await api('/api/state'));if($('login').open)$('login').close();}catch(e){$('connection').textContent='● Worker disconnected';}finally{polling=false;}}
async function loadTests(){if(state?.busy){$('test-list').replaceChildren(el('article','Test-file editing is available when the current operation has finished.'));return;}const data=await api('/api/tests');testData=data.tests;$('example-select').replaceChildren(...data.examples.map(x=>new Option(x,x)));const list=$('test-list');list.replaceChildren();for(const t of data.tests){const card=el('article');card.append(el('h3',t.name||t.id),el('p',t.id+' · '+t.variants.length+' workflow variants · '+(t.repetitions||1)+' repetition(s) · '+(t.enabled===false?'Disabled':'Enabled')));card.append(button('View / edit JSON',()=>openEditor(t)),el('p',t.variants.map(v=>v.id+' ('+v.steps.length+' top-level steps)').join(' · '),'muted'));list.append(card);}}
function openEditor(t){$('test-json').value=JSON.stringify(t,null,2);$('editor').showModal();}
async function loadResults(){if(state?.busy){$('result-list').replaceChildren(el('article','Stop or finish the active run before loading results from disk. Live progress remains available in Overview.'));return;}records=await api('/api/results');renderResults();}
function renderResults(){const search=$('result-filter').value.toLowerCase();const list=$('result-list');list.replaceChildren();for(const r of records.filter(r=>[r.model_id,r.test_id,r.variant_id].join(' ').toLowerCase().includes(search))){const card=el('article',undefined,'result-row');const title=el('div');title.append(el('b',r.model_id),el('p',r.test_id+' / '+r.variant_id,'muted'));const correct=r.score?.exact_match;let label=r.status!=='completed'?r.status:(correct===true?'PASS':correct===false?'FAIL':'NO EXACT ORACLE');if(r.measurement_valid===false)label+=' · INVALID CACHE MEASUREMENT';card.append(title,el('span',label,correct===true?'success':'error'),el('span',typeof r.pipeline_seconds==='number'?r.pipeline_seconds.toFixed(3)+' s':'—'));const act=el('div',undefined,'actions');act.append(button('Inspect',()=>{$('result-json').textContent=JSON.stringify(r,null,2);$('inspect').showModal();}),button('Delete / rerun',async()=>{if(!confirm('Delete this result and make the case pending again? This action is recorded in the audit log.'))return;await api('/api/result/delete',{model_id:r.model_id,case_id:r.case_id});await loadResults();},'danger'));card.append(act);list.append(card);}if(!list.children.length)list.append(el('article','No matching result files.'));}
async function download(path,name){const blob=await api(path);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function browse(path){browseState=await api('/api/browse'+(path?'?path='+encodeURIComponent(path):''));$('browse-path').value=browseState.path;const list=$('browse-items');list.replaceChildren();$('browse-roots').replaceChildren(...browseState.roots.map(r=>button(r,()=>browse(r))));for(const f of browseState.entries){if(!f.directory&&browseTarget==='model-root')continue;list.append(button((f.directory?'▸ ':'')+f.name,()=>{if(f.directory)return browse(f.path);$(browseTarget).value=f.path;setupDirty=true;$('browser').close();}));}$('choose-folder').classList.toggle('hidden',browseTarget!=='model-root');}
async function openBrowse(target){browseTarget=target;await browse(target==='model-root'?$('model-root').value:'');$('browser').showModal();}
on('login-submit',async()=>{key=$('login-key').value.trim();sessionStorage.setItem('rpg-worker-key',key);try{render(await api('/api/state'));$('login').close();}catch(e){$('login-error').textContent=e.message;}});
on('preflight',async()=>{await api('/api/preflight',{});await poll();});on('rescan',async()=>{await api('/api/preflight',{});await poll();});on('run',async()=>{await api('/api/run',{});await poll();});
for(const [id,action] of [['pause','pause'],['resume','resume'],['stop-model','stop_after_model'],['stop','stop']])on(id,()=>api('/api/control',{action}));
on('prepare',()=>api('/api/preflight',{preparation:{gpu_name:$('target-name').value,vram_gb:Number($('target-tier').value)}}));
on('export',()=>download('/api/export','rpg-testing-evidence.zip'));on('unity-script',()=>download('/api/unity-script?tier='+$('target-tier').value,'rpg-unity-job.sh'));
on('refresh-tests',loadTests);on('refresh-results',loadResults);$('result-filter').addEventListener('input',renderResults);
on('import-example',async()=>{await api('/api/test/import-example',{id:$('example-select').value});await loadTests();toast('Example added to test files.');});
on('new-test',()=>openEditor(testData[0]?{...testData[0],id:'new_test',name:'New test'}:{schema_version:2,id:'new_test',workflow:'steps',source:{},variants:[]}));
on('save-test',async()=>{let test;try{test=JSON.parse($('test-json').value);}catch{throw Error('This is not valid JSON.');}await api('/api/test/save',{test});$('editor').close();await loadTests();toast('Test validated and saved.');});
on('save-setup',async()=>{const values={backend:$('backend').value,model_root:$('model-root').value.trim(),lms_path:$('lms-path').value.trim(),llama_path:$('llama-path').value.trim(),sync_source:$('sync-source').checked,publish_results:$('publish-results').checked};if($('api-token').value)values.model_api_token=$('api-token').value;if(values.publish_results&&!state.settings.publish_results&&!confirm('Publish only synthetic safe-for-work results to the public GitHub repository? Do not enable for private data.'))return;await api('/api/settings',values);setupDirty=false;$('api-token').value='';toast('Worker setup saved. Run preflight next.');});
on('browse-models',()=>openBrowse('model-root'));on('browse-lms',()=>openBrowse('lms-path'));on('browse-llama',()=>openBrowse('llama-path'));on('browse-go',()=>browse($('browse-path').value));on('browse-up',()=>browse(browseState.parent));on('choose-folder',()=>{$(browseTarget).value=browseState.path;setupDirty=true;$('browser').close();});
on('enable-remote',async()=>{const r=await api('/api/remote/enable',{});$('remote-url').textContent=r.url;toast('Private controller enabled. Pair your laptop at the displayed address.');});
on('disable-remote',async()=>{if(confirm('Disable remote access? A laptop connection will disconnect, but the local workbench stays available.'))await api('/api/remote/disable',{});});
on('pairing',async()=>{$('pairing-value').textContent=(await api('/api/pairing-key')).key;});
on('close-worker',async()=>{if(confirm('Close the worker service? Remote controls will stop working until it is started again.'))await api('/api/shutdown',{});});
on('restart',async()=>{await api('/api/restart',{});toast('Restarting with the latest code…');setTimeout(()=>location.reload(),2500);});
if(!key)$('login').showModal();else poll();setInterval(poll,1200);
